#!/usr/bin/env bash
# audit-skill.sh
#
# Usage: bash audit-skill.sh <skill-path> [<output-path>]
#
# Produces a structural audit of a SKILL.md to inform compression. The audit
# reports word/line counts, per-section sizes, example-block counts, and
# repeated content — the mechanical signals the LLM compressor uses as a
# starting skeleton for semantic deduplication.
#
# What this script does NOT do (and is not meant to do): semantic analysis of
# whether two rules say the same thing in different words. That is LLM work
# in the compress-mode pipeline. This script narrows the search space; the
# LLM does the judgement.
#
# Output is markdown on stdout (or to <output-path> if given).
#
# Exits 0 on success, 1 on bad arguments. Never modifies the skill itself.

set -euo pipefail

if [[ $# -lt 1 || $# -gt 2 ]]; then
  echo "Usage: $0 <skill-path-or-skill-md-file> [<output-path>]" >&2
  exit 1
fi

skill_arg="$1"
output_path="${2:-}"

# Resolve the SKILL.md path. Accept either the directory containing it or the
# file itself.
if [[ -d "$skill_arg" ]]; then
  skill_md="$skill_arg/SKILL.md"
elif [[ -f "$skill_arg" ]]; then
  skill_md="$skill_arg"
else
  echo "Error: $skill_arg is not a directory or file" >&2
  exit 1
fi

if [[ ! -f "$skill_md" ]]; then
  echo "Error: SKILL.md not found at $skill_md" >&2
  exit 1
fi

# Buffer output so we can write to either stdout or a file.
emit() {
  if [[ -n "$output_path" ]]; then
    printf '%s\n' "$1" >> "$output_path"
  else
    printf '%s\n' "$1"
  fi
}

# Truncate output file if writing to one.
[[ -n "$output_path" ]] && : > "$output_path"

# --- Header ---------------------------------------------------------------
emit "# Skill audit: $skill_md"
emit ""
emit "Generated by audit-skill.sh. Structural defects only — semantic deduplication is LLM work in the compress-mode pipeline."
emit ""

# --- Top-level size --------------------------------------------------------
total_lines=$(wc -l < "$skill_md" | tr -d ' ')
total_words=$(wc -w < "$skill_md" | tr -d ' ')
total_bytes=$(wc -c < "$skill_md" | tr -d ' ')

emit "## Size"
emit ""
emit "| Metric | Value |"
emit "|---|---|"
emit "| Lines | $total_lines |"
emit "| Words | $total_words |"
emit "| Bytes | $total_bytes |"
emit ""

# Suggest a target. Rule of thumb from the pm-writing-standards compression
# session: ~40-60% of current is achievable when section ratios are unbalanced.
target_low=$(( total_words * 4 / 10 ))
target_high=$(( total_words * 6 / 10 ))
emit "Suggested target word count: $target_low to $target_high (40-60% of current). Use the LLM auditor's strategy to set the actual target — this is a heuristic floor."
emit ""

# --- Per-section word counts ----------------------------------------------
# Treat ## and ### headings as section markers. Walk the file and accumulate
# words per section.

emit "## Per-section sizes"
emit ""
emit "| Section | Lines | Words | % of total |"
emit "|---|---|---|---|"

awk -v total_words="$total_words" '
  function flush() {
    if (current_heading != "") {
      pct = (total_words > 0) ? int((current_words * 1000) / total_words) / 10 : 0
      printf("| %s | %d | %d | %s%% |\n", current_heading, current_lines, current_words, pct)
    }
  }
  /^## / || /^### / {
    flush()
    current_heading = $0
    sub(/^#+ /, "", current_heading)
    # Replace pipe characters in the heading so the markdown table parses
    gsub(/\|/, "\\|", current_heading)
    current_lines = 0
    current_words = 0
    next
  }
  {
    if (current_heading != "") {
      current_lines++
      current_words += NF
    }
  }
  END { flush() }
' "$skill_md" | while IFS= read -r row; do
  emit "$row"
done

emit ""

# Section imbalance summary: ratio of largest to smallest section.
read -r max_words min_words <<<"$(awk '
  /^## / || /^### / {
    if (current_heading != "") {
      if (current_words > max) max = current_words
      if (min == 0 || current_words < min) min = current_words
    }
    current_heading = $0
    current_words = 0
    next
  }
  {
    if (current_heading != "") current_words += NF
  }
  END {
    if (current_heading != "") {
      if (current_words > max) max = current_words
      if (min == 0 || current_words < min) min = current_words
    }
    printf("%d %d", max, min)
  }
' "$skill_md")"

if [[ "${min_words:-0}" -gt 0 ]]; then
  ratio_int=$(( max_words / min_words ))
  ratio_remainder=$(( (max_words * 10 / min_words) % 10 ))
  emit "Largest-to-smallest section ratio: ${ratio_int}.${ratio_remainder}× (max=$max_words words, min=$min_words words)."
  if (( ratio_int >= 3 )); then
    emit ""
    emit "**Imbalance flag:** A section is >=3× the size of the smallest. Candidates for compression."
  fi
  emit ""
fi

# --- WRONG/RIGHT example density -------------------------------------------
# Count blocks shaped as `- WRONG:` ... `- RIGHT:` per section. ACTIONs with
# 2+ WRONG/RIGHT pairs are candidates for one-canonical-example compression.

emit "## Example density"
emit ""
emit "Counts of \`- WRONG:\` and \`- RIGHT:\` lines per section. Sections with multiple example pairs per rule are candidates for one-canonical-example compression."
emit ""
emit "| Section | WRONG count | RIGHT count |"
emit "|---|---|---|"

awk '
  function flush() {
    if (current_heading != "") {
      printf("| %s | %d | %d |\n", current_heading, wrong_count, right_count)
    }
  }
  /^## / || /^### / {
    flush()
    current_heading = $0
    sub(/^#+ /, "", current_heading)
    gsub(/\|/, "\\|", current_heading)
    wrong_count = 0
    right_count = 0
    next
  }
  /^[[:space:]]*-?[[:space:]]*\**WRONG/ { wrong_count++ }
  /^[[:space:]]*-?[[:space:]]*\**RIGHT/ { right_count++ }
  END { flush() }
' "$skill_md" | while IFS= read -r row; do
  emit "$row"
done

emit ""

total_wrong=$(grep -cE '^[[:space:]]*-?[[:space:]]*\**WRONG' "$skill_md" || true)
total_right=$(grep -cE '^[[:space:]]*-?[[:space:]]*\**RIGHT' "$skill_md" || true)
emit "Total WRONG examples: $total_wrong. Total RIGHT examples: $total_right."
emit ""

# --- Repeated content ------------------------------------------------------
# Look for the same content line appearing 2+ times. Excludes blank lines,
# lines under 30 chars (too short to be meaningful repeats), table separators
# and code-fence markers.

emit "## Repeated content"
emit ""
emit "Lines (length > 40 chars) that appear 2+ times in the document. Often a signal of cross-section duplication — the same rule restated, or the same example quoted in multiple sections."
emit ""

repeated_output=$(awk '
  length($0) > 40 && !/^[[:space:]]*$/ && !/^[[:space:]]*\|/ && !/^[[:space:]]*```/ && !/^[[:space:]]*-+[[:space:]]*$/ {
    counts[$0]++
  }
  END {
    for (line in counts) {
      if (counts[line] >= 2) {
        printf("%d|%s\n", counts[line], line)
      }
    }
  }
' "$skill_md" | sort -t'|' -k1,1nr | head -20)

if [[ -n "$repeated_output" ]]; then
  emit "| Count | Line (truncated to 100 chars) |"
  emit "|---|---|"
  while IFS='|' read -r count line; do
    truncated="${line:0:100}"
    [[ ${#line} -gt 100 ]] && truncated="${truncated}…"
    # Escape pipes in the content
    truncated_escaped="${truncated//|/\\|}"
    emit "| $count | $truncated_escaped |"
  done <<< "$repeated_output"
else
  emit "_No repeated lines longer than 40 chars detected._"
fi
emit ""

# --- Quoted phrase repetition ----------------------------------------------
# Find quoted phrases (in double-quotes, length > 20) appearing 2+ times.
# These are usually example excerpts copied into multiple rule explanations.

emit "## Repeated quoted phrases"
emit ""
emit "Quoted excerpts (\"...\", length > 20 chars) that appear 2+ times. Common in skills that quote the same WRONG example under multiple rules."
emit ""

# Extract all quoted strings and count duplicates.
quoted_repeats=$(grep -oE '"[^"]{20,}"' "$skill_md" 2>/dev/null \
  | sort | uniq -c \
  | awk '$1 >= 2 { count = $1; sub(/^[[:space:]]*[0-9]+[[:space:]]+/, ""); printf("%d|%s\n", count, $0) }' \
  | sort -t'|' -k1,1nr | head -10 || true)

if [[ -n "$quoted_repeats" ]]; then
  emit "| Count | Quote (truncated to 100 chars) |"
  emit "|---|---|"
  while IFS='|' read -r count quote; do
    truncated="${quote:0:100}"
    [[ ${#quote} -gt 100 ]] && truncated="${truncated}…"
    truncated_escaped="${truncated//|/\\|}"
    emit "| $count | $truncated_escaped |"
  done <<< "$quoted_repeats"
else
  emit "_No repeated quoted phrases longer than 20 chars detected._"
fi
emit ""

# --- Footer ---------------------------------------------------------------
emit "## What the LLM compressor should do with this audit"
emit ""
emit "1. Treat **section imbalance** + **repeated lines/quotes** as compression candidates: collapse cross-section restatements into one canonical location."
emit "2. Treat **WRONG/RIGHT count > 1 per ACTION** as a one-canonical-example candidate: keep the most representative pair, fold the rest into references/ if the catalog is genuinely useful, otherwise delete."
emit "3. Inspect the SKILL.md directly for **semantic duplication** (rules that mean the same thing in different words) and **Quick-Reference / pointer-without-body** defects — those are not detectable structurally and require reading."
emit ""
emit "_End of audit._"
